# Generated by Django 3.0.3 on 2021-04-29 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneAliasesPub',
            fields=[
                ('ga_record_id', models.AutoField(primary_key=True, serialize=False)),
                ('gene_symbol', models.CharField(max_length=500)),
                ('aliases', models.CharField(max_length=500, null=True)),
                ('gene_aliases_note', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
