# Generated by Django 3.2.3 on 2021-05-20 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubad', '0003_pubinfo_year_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pubctd',
            fields=[
                ('pubctd_record_id', models.AutoField(primary_key=True, serialize=False)),
                ('gene_symbol', models.CharField(max_length=100, null=True)),
                ('disease', models.CharField(max_length=100)),
                ('chempub_count', models.JSONField()),
                ('chempub_pmid', models.JSONField()),
                ('inf_score', models.FloatField(null=True)),
            ],
        ),
    ]
