# Generated by Django 3.2.3 on 2021-06-09 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubad', '0004_pubctd'),
    ]

    operations = [
        migrations.AddField(
            model_name='pubinfo',
            name='co_count',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pubinfo',
            name='year_pmid',
            field=models.TextField(default='', max_length=100000),
            preserve_default=False,
        ),
    ]
