# Generated by Django 3.0.3 on 2021-04-29 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PubInfo',
            fields=[
                ('pubinfo_record_id', models.AutoField(primary_key=True, serialize=False)),
                ('gene_symbol', models.CharField(max_length=100, null=True)),
                ('demtype_count', models.CharField(max_length=1000, null=True)),
                ('demtype_pmid', models.TextField(max_length=100000)),
                ('br_count', models.CharField(max_length=1000, null=True)),
                ('br_pmid', models.TextField(max_length=100000)),
                ('mm_count', models.CharField(max_length=1000, null=True)),
                ('mm_pmid', models.TextField(max_length=100000)),
                ('kw_count', models.CharField(max_length=1000, null=True)),
                ('kw_pmid', models.TextField(max_length=100000)),
            ],
        ),
    ]
