# Generated by Django 3.0.3 on 2021-04-29 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubad', '0002_genealiasespub'),
    ]

    operations = [
        migrations.AddField(
            model_name='pubinfo',
            name='year_count',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
