# Generated by Django 3.2.12 on 2022-03-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubad', '0005_auto_20210609_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneInfo',
            fields=[
                ('geneinfo_record_id', models.AutoField(primary_key=True, serialize=False)),
                ('gene_symbol', models.CharField(max_length=100, null=True)),
                ('gene_aliases', models.CharField(max_length=1000, null=True)),
                ('gene_description', models.CharField(max_length=1000, null=True)),
                ('gene_other_designations', models.CharField(max_length=1000, null=True)),
                ('gene_map_location', models.CharField(max_length=100, null=True)),
                ('gene_chromosome', models.CharField(max_length=50, null=True)),
                ('entrez_id', models.CharField(max_length=100, null=True)),
                ('ensembl_id', models.CharField(max_length=100, null=True)),
                ('uniprot_id', models.CharField(max_length=100, null=True)),
                ('refseq_accession', models.CharField(max_length=100, null=True)),
                ('chembl_target_id', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
