# Generated by Django 3.2.12 on 2022-03-02 12:31

from django.core.management import call_command
from django.db import migrations


def load_geneinfo(apps, schema_editor):
    call_command("loaddata", "pubad/GeneInfo_data.json")


class Migration(migrations.Migration):

    dependencies = [
        ("pubad", "0006_geneinfo"),
    ]

    operations = [migrations.RunPython(load_geneinfo, migrations.RunPython.noop)]
